// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MMTShop.Models;

namespace MMTShop.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210627230012_sp-GetProductsByCategory")]
    partial class spGetProductsByCategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EndRange");

                    b.Property<string>("Name");

                    b.Property<int>("StartRange");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, EndRange = 19999, Name = "Home", StartRange = 10000 },
                        new { Id = 2, EndRange = 29999, Name = "Garden", StartRange = 20000 },
                        new { Id = 3, EndRange = 39999, Name = "Electronics", StartRange = 30000 },
                        new { Id = 4, EndRange = 49999, Name = "Fitness", StartRange = 40000 },
                        new { Id = 5, EndRange = 59999, Name = "Toys", StartRange = 50000 }
                    );
                });

            modelBuilder.Entity("ProductManagement.Models.Product", b =>
                {
                    b.Property<int>("Sku")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Sku");

                    b.ToTable("Products");

                    b.HasData(
                        new { Sku = 12000, Category = "Home", Description = "TestA", Name = "A", Price = 100 },
                        new { Sku = 13000, Category = "Home", Description = "TestB", Name = "B", Price = 100 },
                        new { Sku = 22000, Category = "Garden", Description = "TestC", Name = "C", Price = 100 },
                        new { Sku = 23000, Category = "Garden", Description = "TestD", Name = "D", Price = 100 },
                        new { Sku = 32000, Category = "Electronics", Description = "TestE", Name = "E", Price = 100 },
                        new { Sku = 33000, Category = "Electronics", Description = "TestF", Name = "F", Price = 100 },
                        new { Sku = 42000, Category = "Fitness", Description = "TestG", Name = "G", Price = 100 },
                        new { Sku = 43000, Category = "Fitness", Description = "TestH", Name = "H", Price = 100 },
                        new { Sku = 52000, Category = "Toys", Description = "TestI", Name = "I", Price = 100 },
                        new { Sku = 53000, Category = "Toys", Description = "TestJ", Name = "J", Price = 100 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
